// 모든 리그의 선수 로스터 데이터
// 나무위키 링크 기반: LCK, LPL, LCS, CBLOL, LCP

export interface PlayerData {
  name: string;
  position: 'TOP' | 'JUNGLE' | 'MID' | 'ADC' | 'SUPPORT';
  nationality: string;
}

// LCK 선수들
const lckPlayers: PlayerData[] = [
  { name: 'Zeus', position: 'TOP', nationality: 'KR' },
  { name: 'Oner', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Faker', position: 'MID', nationality: 'KR' },
  { name: 'Gumayusi', position: 'ADC', nationality: 'KR' },
  { name: 'Keria', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Doran', position: 'TOP', nationality: 'KR' },
  { name: 'Peanut', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Chovy', position: 'MID', nationality: 'KR' },
  { name: 'Peyz', position: 'ADC', nationality: 'KR' },
  { name: 'Delight', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Kiin', position: 'TOP', nationality: 'KR' },
  { name: 'Canyon', position: 'JUNGLE', nationality: 'KR' },
  { name: 'ShowMaker', position: 'MID', nationality: 'KR' },
  { name: 'Deft', position: 'ADC', nationality: 'KR' },
  { name: 'BeryL', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Cuzz', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Bdd', position: 'MID', nationality: 'KR' },
  { name: 'Aiming', position: 'ADC', nationality: 'KR' },
  { name: 'Lehends', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Rascal', position: 'TOP', nationality: 'KR' },
  { name: 'Clid', position: 'JUNGLE', nationality: 'KR' },
  { name: 'FATE', position: 'MID', nationality: 'KR' },
  { name: 'Teddy', position: 'ADC', nationality: 'KR' },
  { name: 'Kael', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Dudu', position: 'TOP', nationality: 'KR' },
  { name: 'Willer', position: 'JUNGLE', nationality: 'KR' },
  { name: 'BuLLDoG', position: 'MID', nationality: 'KR' },
  { name: 'Envyy', position: 'ADC', nationality: 'KR' },
  { name: 'Baut', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Morgan', position: 'TOP', nationality: 'KR' },
  { name: 'GIDEON', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Callme', position: 'MID', nationality: 'KR' },
  { name: 'Hena', position: 'ADC', nationality: 'KR' },
  { name: 'Irean', position: 'TOP', nationality: 'KR' },
  { name: 'YoungJae', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Karis', position: 'MID', nationality: 'KR' },
  { name: 'Taeyoon', position: 'ADC', nationality: 'KR' },
  { name: 'Peter', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Clear', position: 'TOP', nationality: 'KR' },
  { name: 'Lucid', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Karis', position: 'MID', nationality: 'KR' },
  { name: 'Berserker', position: 'ADC', nationality: 'KR' },
  { name: 'Winsome', position: 'SUPPORT', nationality: 'KR' },
];

// LPL 선수들
const lplPlayers: PlayerData[] = [
  { name: 'Bin', position: 'TOP', nationality: 'CN' },
  { name: 'Wei', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Xiaohu', position: 'MID', nationality: 'CN' },
  { name: 'GALA', position: 'ADC', nationality: 'CN' },
  { name: 'Ming', position: 'SUPPORT', nationality: 'CN' },
  { name: '369', position: 'TOP', nationality: 'CN' },
  { name: 'Kanavi', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Knight', position: 'MID', nationality: 'CN' },
  { name: 'Ruler', position: 'ADC', nationality: 'KR' },
  { name: 'Missing', position: 'SUPPORT', nationality: 'CN' },
  { name: 'TheShy', position: 'TOP', nationality: 'KR' },
  { name: 'Weiwei', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Light', position: 'ADC', nationality: 'CN' },
  { name: 'Crisp', position: 'SUPPORT', nationality: 'CN' },
  { name: 'Ale', position: 'TOP', nationality: 'CN' },
  { name: 'Tarzan', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Scout', position: 'MID', nationality: 'KR' },
  { name: 'GALA', position: 'ADC', nationality: 'CN' },
  { name: 'Hang', position: 'SUPPORT', nationality: 'CN' },
  { name: 'Flandre', position: 'TOP', nationality: 'CN' },
  { name: 'Jiejie', position: 'JUNGLE', nationality: 'CN' },
  { name: 'FoFo', position: 'MID', nationality: 'TW' },
  { name: 'Leave', position: 'ADC', nationality: 'CN' },
  { name: 'Meiko', position: 'SUPPORT', nationality: 'CN' },
  { name: 'Wayward', position: 'TOP', nationality: 'CN' },
  { name: 'Tian', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Rookie', position: 'MID', nationality: 'KR' },
  { name: 'JackeyLove', position: 'ADC', nationality: 'CN' },
  { name: 'Mark', position: 'SUPPORT', nationality: 'CN' },
  { name: 'shanji', position: 'TOP', nationality: 'CN' },
  { name: 'Aki', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Creme', position: 'MID', nationality: 'CN' },
  { name: 'Photic', position: 'ADC', nationality: 'CN' },
  { name: 'ppgod', position: 'SUPPORT', nationality: 'CN' },
  { name: 'Cube', position: 'TOP', nationality: 'CN' },
  { name: 'Xiaohao', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Yagao', position: 'MID', nationality: 'CN' },
  { name: 'Elk', position: 'ADC', nationality: 'CN' },
  { name: 'ON', position: 'SUPPORT', nationality: 'CN' },
  { name: 'Zika', position: 'TOP', nationality: 'CN' },
  { name: 'Leyan', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Yuekai', position: 'MID', nationality: 'CN' },
  { name: 'LP', position: 'ADC', nationality: 'CN' },
  { name: 'Zhuo', position: 'SUPPORT', nationality: 'CN' },
  { name: 'Hery', position: 'TOP', nationality: 'CN' },
  { name: 'H4cker', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Fisher', position: 'MID', nationality: 'KR' },
  { name: 'Assum', position: 'ADC', nationality: 'CN' },
  { name: 'QiuQiu', position: 'SUPPORT', nationality: 'CN' },
  { name: 'Xiaoxu', position: 'TOP', nationality: 'CN' },
  { name: 'Meteor', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Strive', position: 'MID', nationality: 'CN' },
  { name: 'Hope', position: 'ADC', nationality: 'CN' },
  { name: 'Iwandy', position: 'SUPPORT', nationality: 'CN' },
  { name: 'Breathe', position: 'TOP', nationality: 'CN' },
  { name: 'Wei', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Xiaohu', position: 'MID', nationality: 'CN' },
  { name: 'Light', position: 'ADC', nationality: 'CN' },
  { name: 'Crisp', position: 'SUPPORT', nationality: 'CN' },
  { name: 'YSKM', position: 'TOP', nationality: 'CN' },
  { name: 'Ning', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Rookie', position: 'MID', nationality: 'KR' },
  { name: 'Ahn', position: 'ADC', nationality: 'CN' },
  { name: 'Wink', position: 'SUPPORT', nationality: 'CN' },
  { name: 'Zdz', position: 'TOP', nationality: 'CN' },
  { name: 'Xiaohao', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Tangyuan', position: 'MID', nationality: 'CN' },
  { name: 'Light', position: 'ADC', nationality: 'CN' },
  { name: 'Crisp', position: 'SUPPORT', nationality: 'CN' },
];

// LCS 선수들
const lcsPlayers: PlayerData[] = [
  { name: 'Impact', position: 'TOP', nationality: 'KR' },
  { name: 'Blaber', position: 'JUNGLE', nationality: 'NA' },
  { name: 'Jensen', position: 'MID', nationality: 'DK' },
  { name: 'Berserker', position: 'ADC', nationality: 'KR' },
  { name: 'Vulcan', position: 'SUPPORT', nationality: 'CA' },
  { name: 'Ssumday', position: 'TOP', nationality: 'KR' },
  { name: 'Closer', position: 'JUNGLE', nationality: 'TR' },
  { name: 'Quid', position: 'MID', nationality: 'KR' },
  { name: 'FBI', position: 'ADC', nationality: 'AU' },
  { name: 'Huhi', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Revenge', position: 'TOP', nationality: 'NA' },
  { name: 'Contractz', position: 'JUNGLE', nationality: 'NA' },
  { name: 'Palafox', position: 'MID', nationality: 'NA' },
  { name: 'Winsome', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Licorice', position: 'TOP', nationality: 'NA' },
  { name: 'River', position: 'JUNGLE', nationality: 'KR' },
  { name: 'VicLa', position: 'MID', nationality: 'KR' },
  { name: 'Yeon', position: 'ADC', nationality: 'KR' },
  { name: 'Eyla', position: 'SUPPORT', nationality: 'AU' },
  { name: 'Dhokla', position: 'TOP', nationality: 'NA' },
  { name: 'Spica', position: 'JUNGLE', nationality: 'CN' },
  { name: 'Maple', position: 'MID', nationality: 'TW' },
  { name: 'WildTurtle', position: 'ADC', nationality: 'CA' },
  { name: 'Chime', position: 'SUPPORT', nationality: 'NA' },
  { name: 'FakeGod', position: 'TOP', nationality: 'NA' },
  { name: 'Armao', position: 'JUNGLE', nationality: 'NA' },
  { name: 'Ablazeolive', position: 'MID', nationality: 'NA' },
  { name: 'Luger', position: 'ADC', nationality: 'TR' },
  { name: 'Poome', position: 'SUPPORT', nationality: 'CA' },
  { name: 'Solo', position: 'TOP', nationality: 'NA' },
  { name: 'Bugi', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Insanity', position: 'MID', nationality: 'NA' },
  { name: 'Tactical', position: 'ADC', nationality: 'NA' },
  { name: 'Aphromoo', position: 'SUPPORT', nationality: 'NA' },
];

// CBLOL 선수들
const cblolPlayers: PlayerData[] = [
  { name: 'Robo', position: 'TOP', nationality: 'BR' },
  { name: 'Croc', position: 'JUNGLE', nationality: 'BR' },
  { name: 'tinowns', position: 'MID', nationality: 'BR' },
  { name: 'Route', position: 'ADC', nationality: 'BR' },
  { name: 'Ceos', position: 'SUPPORT', nationality: 'BR' },
  { name: 'fNb', position: 'TOP', nationality: 'BR' },
  { name: 'Aegis', position: 'JUNGLE', nationality: 'BR' },
  { name: 'Grevthar', position: 'MID', nationality: 'BR' },
  { name: 'TitaN', position: 'ADC', nationality: 'BR' },
  { name: 'Kuri', position: 'SUPPORT', nationality: 'BR' },
  { name: 'Guigo', position: 'TOP', nationality: 'BR' },
  { name: 'Ranger', position: 'JUNGLE', nationality: 'BR' },
  { name: 'Goku', position: 'MID', nationality: 'BR' },
  { name: 'Brance', position: 'ADC', nationality: 'BR' },
  { name: 'RedBert', position: 'SUPPORT', nationality: 'BR' },
  { name: 'Tay', position: 'TOP', nationality: 'BR' },
  { name: 'Aegis', position: 'JUNGLE', nationality: 'BR' },
  { name: 'Grevthar', position: 'MID', nationality: 'BR' },
  { name: 'Netuno', position: 'ADC', nationality: 'BR' },
  { name: 'Kuri', position: 'SUPPORT', nationality: 'BR' },
  { name: 'Wizer', position: 'TOP', nationality: 'BR' },
  { name: 'Cariok', position: 'JUNGLE', nationality: 'BR' },
  { name: 'dyNquedo', position: 'MID', nationality: 'BR' },
  { name: 'Trigo', position: 'ADC', nationality: 'BR' },
  { name: 'Jojo', position: 'SUPPORT', nationality: 'BR' },
  { name: 'Tay', position: 'TOP', nationality: 'BR' },
  { name: 'Aegis', position: 'JUNGLE', nationality: 'BR' },
  { name: 'Grevthar', position: 'MID', nationality: 'BR' },
  { name: 'Netuno', position: 'ADC', nationality: 'BR' },
  { name: 'Kuri', position: 'SUPPORT', nationality: 'BR' },
];

// LCP (PCS) 선수들
const lcpPlayers: PlayerData[] = [
  { name: 'Azhi', position: 'TOP', nationality: 'TW' },
  { name: 'Karsa', position: 'JUNGLE', nationality: 'TW' },
  { name: 'Maple', position: 'MID', nationality: 'TW' },
  { name: 'Betty', position: 'ADC', nationality: 'TW' },
  { name: 'SwordArt', position: 'SUPPORT', nationality: 'TW' },
  { name: 'Hanabi', position: 'TOP', nationality: 'TW' },
  { name: 'Junjia', position: 'JUNGLE', nationality: 'TW' },
  { name: 'Mission', position: 'MID', nationality: 'TW' },
  { name: 'Shunn', position: 'ADC', nationality: 'TW' },
  { name: 'Woody', position: 'SUPPORT', nationality: 'TW' },
  { name: 'Likai', position: 'TOP', nationality: 'CN' },
  { name: 'Gemini', position: 'JUNGLE', nationality: 'TW' },
  { name: 'Ubao', position: 'MID', nationality: 'TW' },
  { name: 'Wako', position: 'ADC', nationality: 'JP' },
  { name: 'Tide', position: 'SUPPORT', nationality: 'TW' },
  { name: 'Driver', position: 'TOP', nationality: 'TW' },
  { name: 'Husha', position: 'JUNGLE', nationality: 'TW' },
  { name: '1111', position: 'MID', nationality: 'TW' },
  { name: 'Atlen', position: 'ADC', nationality: 'TW' },
  { name: 'Kino', position: 'SUPPORT', nationality: 'TW' },
  { name: 'Solokill', position: 'TOP', nationality: 'TW' },
];

// VCS 선수들
const vcsPlayers: PlayerData[] = [
  { name: 'Kiaya', position: 'TOP', nationality: 'VN' },
  { name: 'Levi', position: 'JUNGLE', nationality: 'VN' },
  { name: 'Gloryy', position: 'MID', nationality: 'VN' },
  { name: 'Slayder', position: 'ADC', nationality: 'VN' },
  { name: 'Palette', position: 'SUPPORT', nationality: 'VN' },
  { name: 'Hani', position: 'TOP', nationality: 'VN' },
  { name: 'BeanJ', position: 'JUNGLE', nationality: 'VN' },
  { name: 'Froggy', position: 'MID', nationality: 'VN' },
  { name: 'Artemis', position: 'ADC', nationality: 'VN' },
  { name: 'Bie', position: 'SUPPORT', nationality: 'VN' },
  { name: 'Zeros', position: 'TOP', nationality: 'VN' },
  { name: 'Draktharr', position: 'JUNGLE', nationality: 'VN' },
  { name: 'Kati', position: 'MID', nationality: 'VN' },
  { name: 'Shogun', position: 'ADC', nationality: 'VN' },
  { name: 'Taki', position: 'SUPPORT', nationality: 'VN' },
  { name: 'Hasmed', position: 'TOP', nationality: 'VN' },
  { name: 'SofM', position: 'JUNGLE', nationality: 'VN' },
];

// LJL 선수들
const ljlPlayers: PlayerData[] = [
  { name: 'Evi', position: 'TOP', nationality: 'JP' },
  { name: 'Steal', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Aria', position: 'MID', nationality: 'KR' },
  { name: 'Yutapon', position: 'ADC', nationality: 'JP' },
  { name: 'Harp', position: 'SUPPORT', nationality: 'JP' },
  { name: 'apaMEN', position: 'TOP', nationality: 'JP' },
  { name: 'Ace', position: 'JUNGLE', nationality: 'JP' },
  { name: 'Ceros', position: 'MID', nationality: 'JP' },
  { name: 'Yutapon', position: 'ADC', nationality: 'JP' },
  { name: 'Gaeng', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Vivid', position: 'TOP', nationality: 'JP' },
  { name: 'Aria', position: 'MID', nationality: 'KR' },
  { name: 'Yutapon', position: 'ADC', nationality: 'JP' },
  { name: 'Harp', position: 'SUPPORT', nationality: 'JP' },
  { name: 'Kinatu', position: 'TOP', nationality: 'JP' },
  { name: 'Blank', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Aria', position: 'MID', nationality: 'KR' },
  { name: 'Yutapon', position: 'ADC', nationality: 'JP' },
  { name: 'Harp', position: 'SUPPORT', nationality: 'JP' },
];

// LEC 선수들
const lecPlayers: PlayerData[] = [
  { name: 'Caps', position: 'MID', nationality: 'DK' },
  { name: 'Humanoid', position: 'MID', nationality: 'CZ' },
  { name: 'Elyoya', position: 'JUNGLE', nationality: 'ES' },
  { name: 'Upset', position: 'ADC', nationality: 'DE' },
  { name: 'Hylissang', position: 'SUPPORT', nationality: 'BG' },
  { name: 'Wunder', position: 'TOP', nationality: 'DK' },
  { name: 'Jankos', position: 'JUNGLE', nationality: 'PL' },
  { name: 'Perkz', position: 'MID', nationality: 'HR' },
  { name: 'Rekkles', position: 'ADC', nationality: 'SE' },
  { name: 'Mikyx', position: 'SUPPORT', nationality: 'SI' },
  { name: 'Odoamne', position: 'TOP', nationality: 'RO' },
  { name: 'Malrang', position: 'JUNGLE', nationality: 'KR' },
  { name: 'Larssen', position: 'MID', nationality: 'SE' },
  { name: 'Comp', position: 'ADC', nationality: 'GR' },
  { name: 'Trymbi', position: 'SUPPORT', nationality: 'PL' },
  { name: 'Adam', position: 'TOP', nationality: 'FR' },
  { name: 'Razork', position: 'JUNGLE', nationality: 'ES' },
  { name: 'Vetheo', position: 'MID', nationality: 'FR' },
  { name: 'Neon', position: 'ADC', nationality: 'CZ' },
  { name: 'Targamas', position: 'SUPPORT', nationality: 'BE' },
  { name: 'Oscarinin', position: 'TOP', nationality: 'ES' },
  { name: 'Razork', position: 'JUNGLE', nationality: 'ES' },
  { name: 'Humanoid', position: 'MID', nationality: 'CZ' },
  { name: 'Noah', position: 'ADC', nationality: 'KR' },
  { name: 'Jun', position: 'SUPPORT', nationality: 'KR' },
  { name: 'Chasy', position: 'TOP', nationality: 'KR' },
  { name: 'Elyoya', position: 'JUNGLE', nationality: 'ES' },
  { name: 'FEBIVEN', position: 'MID', nationality: 'ES' },
  { name: 'Flakked', position: 'ADC', nationality: 'ES' },
  { name: 'Mersa', position: 'SUPPORT', nationality: 'GR' },
];

// 모든 선수 합치기 (중복 제거)
export function getAllPlayers(): PlayerData[] {
  const allPlayers = [
    ...lckPlayers,
    ...lplPlayers,
    ...lcsPlayers,
    ...cblolPlayers,
    ...lcpPlayers,
    ...vcsPlayers,
    ...ljlPlayers,
    ...lecPlayers,
  ];

  // 이름 기준으로 중복 제거
  const uniquePlayers = new Map<string, PlayerData>();
  for (const player of allPlayers) {
    if (!uniquePlayers.has(player.name)) {
      uniquePlayers.set(player.name, player);
    }
  }

  return Array.from(uniquePlayers.values());
}

